name: CI

on: [push]

jobs:
  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Do not convert LF to CRLF on checkout
        run: |
          git config core.autocrlf false
          git checkout .

      - name: Build setup
        run: ./build
        shell: powershell